"""Perception and action, one step removed from any particular UI technology.

``protocol`` holds the vocabulary, ``a11y`` turns an accessibility snapshot
into it, ``locators`` finds a control four increasingly desperate ways,
``conditions`` says what a step is waiting for, and ``playwright_surface`` is
the one implementation that touches a browser.
"""

from cua.surface.conditions import (
    AllOf,
    AnyOf,
    Condition,
    ErrorBannerPresent,
    LocationMatches,
    OutputExtracted,
    RegionPresent,
    TextPresent,
    ValidationMessagePresent,
    ValueSet,
    Visible,
)
from cua.surface.locators import (
    Ambiguous,
    BBox,
    Ladder,
    LadderOutcome,
    NearText,
    Resolved,
    RoleName,
    TableCell,
    Unresolved,
    Within,
    resolve_ladder,
)
from cua.surface.protocol import (
    Action,
    ActionFailed,
    ActionResult,
    Click,
    ConditionTimeout,
    FrameInfo,
    Navigate,
    Node,
    Observation,
    PerceptionDrift,
    Press,
    ReadText,
    RecordingEnv,
    Rect,
    SelectOption,
    SessionHandle,
    StaleRefError,
    Surface,
    SurfaceError,
    TypeText,
    Viewport,
)

__all__ = [
    "Action",
    "ActionFailed",
    "ActionResult",
    "AllOf",
    "Ambiguous",
    "AnyOf",
    "BBox",
    "Click",
    "Condition",
    "ConditionTimeout",
    "ErrorBannerPresent",
    "FrameInfo",
    "Ladder",
    "LadderOutcome",
    "LocationMatches",
    "Navigate",
    "NearText",
    "Node",
    "Observation",
    "OutputExtracted",
    "PerceptionDrift",
    "Press",
    "ReadText",
    "RecordingEnv",
    "Rect",
    "RegionPresent",
    "Resolved",
    "RoleName",
    "SelectOption",
    "SessionHandle",
    "StaleRefError",
    "Surface",
    "SurfaceError",
    "TableCell",
    "TextPresent",
    "TypeText",
    "Unresolved",
    "ValidationMessagePresent",
    "ValueSet",
    "Viewport",
    "Visible",
    "Within",
    "resolve_ladder",
]
